import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import {
  fontCaveat,
  fontPpFragmentGlare,
  fontRobotoMono,
} from "@/assets/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "antialiased",
          fontRobotoMono.variable,
          fontPpFragmentGlare.variable,
          fontCaveat.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
